version: '3.7'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - "ZOOKEEPER_CLIENT_PORT=2181"
      - "ZOOKEEPER_TICK_TIME=2000"
#    networks:
#      - sparknet

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - "KAFKA_BROKER_ID=1"
      - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"
      - "KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      - "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      - "KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT"
      - "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1"
#    networks:
#      - sparknet

  spark-master:
    build: docker/spark
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./late-events/script:/spark-2.4.0/late-events
    environment:
      - "KAFKA_BOOTSTRAP_SERVERS=kafka:29092"


  spark-worker-1:
    build: docker/spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker -c 2 -m 2G spark://spark-master:7077
    ports:
      - "8081:8081"

#  spark-master:
#    image: dsncode/spark-master
#    hostname: master
#    ports:
#      - "8080:8080"
#      - "7077:7077"
#    networks:
#      - sparknet
#    volumes:
#      - ./late-events/script:/app/spark-2.4.0-bin-hadoop2.7/late-events
#    environment:
#      - "KAFKA_BOOTSTRAP_SERVERS=kafka:29092"
#
#
#  spark-slave:
#    image: dsncode/spark-slave
#    depends_on:
#      - spark-master
#    ports:
#      - "8081:8081"
#    environment:
#      - "SPARK_MASTER=spark-master:7077"
#    deploy:
#      replicas: 1 # change to any number of necessary replicas
#    networks:
#      - sparknet
#    volumes:
#      - ./late-events/script:/app/spark-2.4.0-bin-hadoop2.7/late-events
#
#  cassandra:
#    image: spotify/cassandra

#networks:
#  sparknet:
